import type { Metadata } from "next";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import "./globals.css";
import { SearchProvider } from "@/context/SearchContext";



export const metadata: Metadata = {
  title: "Meals App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SearchProvider>
          <Header/>
            {children}
          <Footer/>
        </SearchProvider>
      </body>
    </html>
  );
}
